server:
  contextPath: /uaa
  port: 9999

security:
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico

theflies:
  dbUri: bolt://neo4j:123456@localhost
  dbDriverClassName: org.neo4j.ogm.drivers.bolt.driver.BoltDriver
  dbUsername: neo4j
  dbPassword: 123456


logging.level:
  org.springframework.data: WARN
  org.springframework.security: DEBUG
  com.tma.dc4b: DEBUG