server:
  contextPath: /uaa
  port: 9999

security:
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico

spring.data.neo4j:
  uri: bolt://neo4j:123456@localhost
  session.scope: session

logging.level:
  org.neo4j: DEBUG
  org.springframework.data: DEBUG
  org.springframework.security: DEBUG
  com.tma.dc4b: DEBUG